const minecraftSplashes = [
  "ERES TÚ",
  "¡Como se ve en la televisión!",
  "¿El fin?",
  "No debe reproducirse mientras se conduce.",
  "¡1% de azúcar!",
  "¡Ph1lza tuvo una buena racha!",
  "¡Impresionante!",
  "¡100% puro!",
  "¡Puede contener frutos secos!",
  "¡Todo está lleno de amor!",
  "¡Más polígonos!",
  "¡Edición limitada!",
  "¡Letras parpadeantes!",
  "¡Hecho por Notch!",
  "¡Ya está aquí!",
  "¡Deja esa galleta!",
  "¡El mejor de su clase!",
  "¡Está terminado!",
  "¡Una especie de dragón libre!",
  "¡Te llamo mamá!",
  "¡Excitación!",
  "¡Más de 500 vendidos!",
  "¡Único en su clase!",
  "¡Montones de visitas en YouTube!",
  "¡Desarrollo independiente!",
  "¡Arañas por todas partes!",
  "¡Échale un vistazo!",
  "¡Santo cielo, hombre!",
  "¡Es un juego!",
  "¡Hecho en Suecia!",
  "¡Utiliza LWJGL!",
  "¡Splines reticuladas!",
  "¡Minecraft!",
  "¡Yaaay!",
  "¡Un jugador!",
  "¡Compatible con teclado!",
  "¡Sin documentación!",
  "¡Lingotes!",
  "¡Creepers explosivos!",
  "¡Eso no es la luna!",
  "¡L33t!",
  "¡Crear!",
  "¡Sobrevivir!",
  "¡Mazmorra!",
  "¡Exclusivo!",
  "¡Lo máximo!",
  "¡Abajo la OPP!",
  "¡Código cerrado!",
  "¡De buen tono!",
  "¡Guau!",
  "¡No está en Steam!",
  "¡Oh, hombre!",
  "¡Una comunidad increíble!",
  "¡Píxeles!",
  "¡Teetsuuuuoooo!",
  "¡Kaaneeeedaaaa!",
  "¡Ahora con dificultad!",
  "¡Mejorado!",
  "¡90% libre de errores!",
  "¡Bonito!",
  "¡12 hierbas y especias!",
  "¡Sin grasa!",
  "¡Absolutamente nada de memes!",
  "¡Odontología gratuita!",
  "¡Pregúntale a tu médico!",
  "¡Menores bienvenidos!",
  "¡Computación en la nube!",
  "¡Legal en Finlandia!",
  "¡Difícil de etiquetar!",
  "¡Técnicamente bien!",
  "¡Trayendo el pan a casa!",
  "¡Indie!",
  "¡Juego del año!",
  "¡Ceci n'est pas una pantalla de título!",
  "¡Euclidiano!",
  "¡Ahora en 3D!",
  "¡Inspirador!",
  "¡Herregud!",
  "¡Autómatas celulares complejos!",
  "¡Sí, señor!",
  "¡Interpretado por vaqueros!",
  "OpenGL 1.2!",
  "¡Miles de colores!",
  "¡Pruébalo!",
  "¡Age of Wonders es mejor!",
  "¡Prueba el guiso de champiñones!",
  "¡Sensacional!",
  "¡Tamal caliente, tamal caliente, caliente!",
  "¡Despídelo, gato del teclado!",
  "¡Garantizado!",
  "¡Macroscópico!",
  "¡Dale!",
  "¡Salpicadura aleatoria!",
  "¡Llama a tu madre!",
  "¡Lucha interna monstruosa!",
  "¡Amado por millones!",
  "¡Edición definitiva!",
  "¡Espeluznante!",
  "¡Tienes una llave nueva!",
  "¡Impermeable!",
  "¡No inflamable!",
  "¡Guau, tío!",
  "¡Todo incluido!",
  "¡Cuéntaselo a tus amigos!",
  "¡NP no está en P!",
  "Notch <3 ¡ez!",
  "¡Música de C418!",
  "¡Transmitido en vivo!",
  "¡Obsesionado!",
  "¡Polinomio!",
  "¡Terrestre!",
  "¡Lleno de estrellas!",
  "¡Científico!",
  "¡Más genial que Spock!",
  "¡Colabora y escucha!",
  "¡Nunca caves hacia abajo!",
  "¡Tómate descansos frecuentes!",
  "¡No es lineal!",
  "¡Han disparó primero!",
  "¡Encantado de conocerlo!",
  "¡Cubos de lava!",
  "¡Monta el cerdo!",
  "¡Más grande que la Tierra!",
  "sqrt(-1) ¡Te amo!",
  "¡Anomalía de Fobos!",
  "¡Golpeando madera!",
  "¡Cayendo por los acantilados!",
  "¡150% de hipérbole!",
  "¡Sinécdoque!",
  "¡Bailemos!",
  "¡Actualización secreta del viernes!",
  "¡Implementación de referencia!",
  "¡Obsceno con dos tipos con comida!",
  "¡Besa el cielo!",
  "20 ¡Vaya al 10!",
  "¡Integración de Verlet!",
  "¡Peter Griffin!",
  "¡No distribuir!",
  "Cogito ergo sum!",
  "[[]] líneas de código!",
  "¡Salió un esqueleto!",
  "¡La obra de Notch!",
  "¡La suma de sus partes!",
  "¡BTAF solía ser bueno!",
  "¡Echo de menos a ADOM!",
  "umop-apisdn!",
  "OICU812!",
  "¡Tráeme Ray Cokes!",
  "¡Para chuparse los dedos!",
  "¡Temático!",
  "¡Neumático!",
  "¡Sublime!",
  "¡Octagonal!",
  "¡Una baguette!",
  "¡Gargamel lo toca!",
  "¡Rita es la nueva jefa!",
  "¡SWM para siempre!",
  "¡Representando a Edsbyn!",
  "¡Matt Damon!",
  "¡Supercalifragilísticoexpialidoso!",
  "¡V consumados!",
  "¡Herramientas para vacas!",
  "¡Doble búfer!",
  "¡Fan fiction!",
  "¡Jason! ¡Jason! ¡Jason!",
  "¡Más caliente que el sol!",
  "¡Con conexión a Internet!",
  "¡Autónomo!",
  "¡Comprometer!",
  "¡Fantasía!",
  "¡DRR! ¡DRR! ¡DRR!",
  "¡Pégale una patada en la raíz!",
  "¡Recursos regionales!",
  "¡Woo, puñetazo en la cara!",
  "¡Woo, algo horrible!",
  "¡Woo, /v/!",
  "¡Woo, tigsource!",
  "¡Woo, foro de Minecraft!",
  "¡Woo, worldofminecraft!",
  "¡Woo, Reddit!",
  "¡Woo, 2pp!",
  "¡Google Analytics lo ha analizado!",
  "¡Ahora es compatible con åäö!",
  "¡Danos a Gordon!",
  "¡Dale propina al camarero!",
  "¡Muy divertido!",
  "¡12345 es una contraseña incorrecta!",
  "¡Vota por la neutralidad de la red!",
  "¡Vive en una piña bajo el mar!",
  "¡MAP11 tiene dos nombres!",
  "¡Omnipotente!",
  "¡Jadear!",
  "...",
  "¡Abejas, abejas, abejas, abejas!",
  "¡Jag känner en bot! (¡Siento una cura!)",
  "Este texto es difícil de leer si juegas con la resolución predeterminada, ¡pero a 1080p se ve bien!",
  "Jaja, ¡jajaja!",
  "¡Baile del hámster!",
  "¡Interruptores y minerales!",
  "¡Esponja Menger!",
  "idspispopd!",
  "Eple (edición original)!",
  "¡Tan fresco, tan limpio!",
  "¡Portales de funcionamiento lento!",
  "¡Prueba el Nether!",
  "¡No mires directamente a los insectos!",
  "¡Oh, vale, Pigmen!",
  "¡Por fin con escaleras!",
  "¡Aterrador!",
  "¡Juega Minecraft, mira Topgear, consigue un cerdo!",
  "¡Lo publicaron en Twitter!",
  "¡Salta, salta y baja!",
  "¡Joel es genial!",
  "¡Un acertijo envuelto en un misterio!",
  "¡Enormes extensiones de tierra!",
  "¡Bienvenido a tu perdición!",
  "¡Quédate un tiempo, quédate para siempre!",
  "¡Quédate un rato y escucha!",
  "¡Tratamiento para tu sarpullido!",
  "¡\"Autológico\" es!",
  "¡La información quiere ser libre!",
  "¡\"Casi nunca\" es un concepto interesante!",
  "¡Muchas verdades!",
  "¡El Creeper es un espía!",
  "¡Turing completa!",
  "¡Es revolucionario!",
  "¡Que comience nuestra batalla!",
  "¡El cielo es el límite!",
  "¡Jeb tiene un pelo increíble!",
  "¡Juegos casuales!",
  "¡Invictos!",
  "¡Algo así como los Lemmings!",
  "¡Sigue el tren, CJ!",
  "¡Aprovechando la sinergia!",
  "Este mensaje nunca aparecerá en la pantalla de inicio, ¿no es raro? (Este mensaje no aparecerá en la pantalla de inicio de Minecraft . Solo se puede ver en los archivos de texto de la pantalla de inicio de Minecraft ).",
  "¡DungeonQuest es unfair!",
  "¡110813!",
  "¡90210!",
  "¡Explora las tierras lejanas!",
  "¡A Tyrion le encantaría!",
  "¡Prueba también VVVVVV!",
  "¡Prueba también Super Meat Boy!",
  "¡Prueba también Terraria!",
  "¡Prueba también Mount & Blade!",
  "¡Prueba también Project Zomboid!",
  "¡Prueba también World of Goo!",
  "¡Prueba también el limbo!",
  "¡Prueba también Pixeljunk Shooter!",
  "¡Prueba también Braid!",
  "¡Eso es genial!",
  "¡El pan es dolor!",
  "¡Lee más libros!",
  "¡Khaaaaaaaaan!",
  "¡Menos adictivo que TV Tropes!",
  "¡Más adictivo que la limonada!",
  "¡Más grande que una caja de pan!",
  "¡Millones de duraznos!",
  "¡Fnord!",
  "¡Esta es mi verdadera forma!",
  "¡Me había olvidado por completo de Dre!",
  "¡No te molestes con los clones!",
  "¡Cabeza de calabaza!",
  "¡Vagabundo follando con una zorra!",
  "¡Hecho por Jeb!",
  "¡Tiene un final!",
  "¡Finalmente terminado!",
  "¡Repleto de funciones!",
  "¡Botas con pelo!",
  "¡Alto, hora de martillar!",
  "¡Testimonios!",
  "¡Convencional!",
  "¡Homeomorfo a una 3-esfera!",
  "¡No evita las dobles negaciones!",
  "¡Coloca TODOS los bloques!",
  "¡Hace giros de barril!",
  "¡Cumpliendo con las expectativas!",
  "¡Juegos de PC desde 1873!",
  "¡Ghoughpteighbteau tchoghs!",
  "¡Déjà vu!",
  "¡Te pillé la nariz!",
  "¡A Haley le encanta Elan!",
  "¡Le tengo miedo al murciélago grande y negro!",
  "¡No usa la palabra con U!",
  "¡Juego de niños!",
  "¡Nos vemos el próximo viernes o algo así!",
  "¡Desde las calles de Södermalm!",
  "¡150 pulsaciones por minuto durante 400.000 minutos!",
  "¡Tecnológico!",
  "¡Funk soul, hermano!",
  "¡Pumpa kungen!",
  "日本ハロー！",
  "한국 안녕하세요!",
  "¡Hola Gales!",
  "¡Hola Polonia!",
  "你好中国！",
  "Привет Россия!",
  "Γεια σου ελλάδα!",
  "¡Mi vida por Aiur!",
  "Lennart lennart = nuevo Lennart();",
  "¡Veo que tu vocabulario ha mejorado!",
  "¿Quién lo puso ahí?",
  "¡No puedes explicar eso!",
  "Si no está bien, entonces regresar.",
  "§1C§2o§3l§4o§5r§6m§7a§8t§9i§ac",
  "§kFUNKY LOL",
  "¡Sabor sin condimentos!",
  "Extraño, ¡pero no un desconocido!",
  "¡Más resistente que los diamantes, rico como la crema!",
  "¡Preparándonos para el espectáculo!",
  "¡Preparándonos para saberlo!",
  "¡Preparándonos para el lanzamiento!",
  "¡Prepárense para impactar!",
  "¡Preparándonos para enloquecer!",
  "¡Preparándome para hablar!",
  "¡Tiene ritmo, tiene swing!",
  "¡Recorriendo las calles en busca de oro!",
  "¡Coge una batidora de huevos y golpéala contra una sartén!",
  "¡Hazme una mesa, una mesa original!",
  "¡Sube en ascensor hasta el entresuelo!",
  "¡Deja de ser razonable, esto es Internet!",
  "/darle abrazos a @a 64",
  "Esto es bueno para Realms.",
  "¡Cualquier ordenador es un portátil si eres lo suficientemente valiente!",
  "¡Hazlo todo, absolutamente todo!",
  "¡Where there is no light, there can be spiders!",
  "GNU Terry Pratchett",
  "¡Más digital!",
  "¡Cayendo con estilo!",
  "No hay quien detenga al Trollmaso.",
  "Tírate al suelo y falla.",
  "Regla número 1: nunca es mi culpa",
  "¿Sustituiste el queso fundido por sangre?",
  "Coordenadas relativamente rotas corregidas por completo",
  "¡Los barcos son lo máximo!",
  "Edición Javalicious",
  "¡No se debe reproducir mientras se conduce!",
  "¡Vas demasiado rápido!",
  "¡No les des chocolate a los loros!",
  "El verdadero significado de covfefe",
  "¡Una ilusión! ¿Qué escondes?",
  "Algo no está del todo bien...",
  "¡Lucha interna monstruosa!",
  "falta",
  "Por si no resulta obvio, los zorros no son jugadores.",
  "¡Abejas zumbadoras!",
  "Minecraft Java Edition presenta: Bichos repugnantes",
  "¡Equipo Místico!",
  "¡Hamilton!",
  "(Prueba beta de Bedrock Edition) ¡Beta!",
  "¡Absolutamente nada de memes!"
];

const FirstPhrase = () => {
    const YText = document.getElementById("YellowText");
    YText.innerHTML = minecraftSplashes[parseInt(Math.random()*minecraftSplashes.length)];
;
}

FirstPhrase();